trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

variables:
  BuildConfiguration: 'Release'
  NukeBuildDirectory: 'build'
  NukeBuildScript: 'build.ps1'
  NukeFile: '.nuke'

  VersionFile: 'release.version'
  GitVersion: $(GitVersion.MajorMinorPatch)
  BuildSuffix: $[counter(variables['GitVersion'], 0)]
  BuildVersion: $(GitVersion)-$(BuildSuffix)
  
  GitFolder: '.git'
  SolutionFile: 'Wcf.Interceptor.Module.sln'
  SourceDirectory: 'src'

steps:
- task: GitVersion@4
  displayName: 'GitVersion'
  inputs:
    updateAssemblyInfo: true

- script: echo %Action%%BuildVersion%
  displayName: 'Set build version'
  env:
    Action: '##vso[build.updatebuildnumber]'
    BuildVersion: $(BuildVersion)

- task: NuGetToolInstaller@1
    
- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: 'build.ps1'
    arguments: 'Compile --Configuration $(BuildConfiguration)'

- task: CopyFiles@2
  displayName: 'Copy Nuke dependencies into staging directory for publishing purposes'
  inputs:
    Contents: |
     $(NukeFile)
     $(VersionFile)
     $(NukeBuildScript)
     $(SolutionFile)
     $(SourceDirectory)/**
     $(NukeBuildDirectory)\**
     $(GitFolder)\**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Packed Artifacts from staging directory'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: publish


