trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

variables:
  BuildConfiguration: 'Release'
  NukePublishDirectory: 'artifacts'
  NukeBuildDirectory: 'build'
  NukeBuildScript: 'build.ps1'
  NukeFile: '.nuke'
  GitFolder: '.git'
  SolutionFile: 'Wcf.Interceptor.Module.sln'
  GitVersionFile: 'GitVersion.yml'

steps:
- task: NuGetToolInstaller@1
- powershell: ls

- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: 'build.ps1'
    arguments: 'Pack --Configuration $(BuildConfiguration)'

- task: CopyFiles@1
  displayName: 'Copy $(NukeBuildDirectory) into $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: $(NukeBuildDirectory)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy $(NukeFile) into $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: $(NukeFile)
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy $(GitVersionFile) into $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: $(GitVersionFile)
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy $(GitFolder) into $(Build.ArtifactStagingDirectory) for git release purposes'
  inputs:
    Contents: $(GitFolder)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy $(NukeBuildScript) into $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: $(NukeBuildScript)
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy $(SolutionFile) into $(Build.ArtifactStagingDirectory) (just for nuke purposes)'
  inputs:
    Contents: $(SolutionFile)
    TargetFolder: $(Build.ArtifactStagingDirectory)



- task: CopyFiles@1
  displayName: 'Copy $(NukePublishDirectory) into $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: $(NukePublishDirectory)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Packed Artifacts from $(Build.ArtifactStagingDirectory)'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: publish


