trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

variables:
  BuildConfiguration: 'Release'
  ArtifactsDirectory: 'artifacts'

steps:
- task: NuGetToolInstaller@1

- powershell: ls

- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: 'build.ps1'
    arguments: 'Pack --Configuration $(BuildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Packed Artifacts'
  inputs:
    PathtoPublish: "$(ArtifactsDirectory)"
    ArtifactName: artifacts


