trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

variables:
  BuildConfiguration: 'Release'
  NukePublishDirectory: 'artifacts'
  NukeBuildDirectory: 'build'
  NukeBuildScript: 'build.ps1'
  NukeFile: '.nuke'
  GitFolder: '.git'
  SolutionFile: 'Wcf.Interceptor.Module.sln'

steps:
- task: NuGetToolInstaller@1
- powershell: ls
- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: 'build.ps1'
    arguments: 'Pack --Configuration $(BuildConfiguration)'

- task: CopyFiles@1
  displayName: 'Copy nuke build project into staging directory'
  inputs:
    Contents: $(NukeBuildDirectory)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy .nuke file into staging directory'
  inputs:
    Contents: $(NukeFile)
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy build script(ps1) into staging directory'
  inputs:
    Contents: $(NukeBuildScript)
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy solution file into staging directory (just for nuke purposes)'
  inputs:
    Contents: $(SolutionFile)
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: CopyFiles@1
  displayName: 'Copy .git file into staging directory for git release purposes'
  inputs:
    Contents: $(GitFile)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)
    SourceFolder: $(GitFile)

- task: CopyFiles@1
  displayName: 'Copy artifacts into staging directory'
  inputs:
    Contents: $(NukePublishDirectory)\**
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Packed Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: publish


