trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

variables:
  BuildConfiguration: 'Release'
  NukePublishDirectory: 'artifacts'

steps:
- task: NuGetToolInstaller@1

- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: 'build.ps1'
    arguments: 'Pack --Configuration $(BuildConfiguration)'

- task: CopyFiles@1
  displayName: 'Copy artifacts into staging directory'
  inputs:
    Contents: $(NukePublishDirectory)\*.nupkg
    TargetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Packed Artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: publish


