trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

steps:
- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: './build.ps1 Pack --Configuration $(Configuration)'
