trigger:
  branches:
    include:
    - master

pool:
  vmImage: vs2017-win2016

variables:
  BuildConfiguration: 'Release'

steps:
- powershell: ls
- task: PowerShell@2
  displayName: 'Executing Nuke Build'
  inputs:
    filePath: 'build.ps1 Pack --Configuration $(BuildConfiguration)'
